[[- $app := ds "app" -]]
[[- $runtime := "scratch" -]]
[[- if conv.ToBool (index $app "distrolessOnly") -]][[- $runtime = $app.distrolessImage -]][[- end -]]
[[- if and (conv.ToBool (index $app "distrolessOnly")) (conv.ToBool (index $app "cgoEnabled")) -]][[- $runtime = strings.ReplaceAll "static-" "base-" $runtime -]][[- end -]]
# runtime image
FROM [[$runtime]]
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/[[$app.binary]] /go/bin/[[$app.binary]]
# Expose port for publishing as web service
[[- if index $app "port" ]]
EXPOSE [[$app.port]]
[[- else ]]
# EXPOSE 8081
[[- end ]]
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/[[$app.binary]]"]
