[[- $app := ds "app" -]]
[[- $cgo := "0" -]]
[[- if conv.ToBool (index $app "cgoEnabled") -]][[- $cgo = "1" -]][[- end -]]
[[- /* CGO binaries need glibc, so swap the static distroless base for the glibc "base" variant. */ -]]
[[- $distroless := $app.distrolessImage -]]
[[- if eq $cgo "1" -]][[- $distroless = strings.ReplaceAll "static-" "base-" $distroless -]][[- end -]]
# setup project and deps
FROM [[$app.goImage]] AS init

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

WORKDIR /workspace/

COPY go.mod* go.sum* ./
RUN go mod download

# Copy only the selected app and shared packages so unrelated apps/* stay out of the build context
COPY [[$app.path]] ./[[$app.path]]
COPY pkg ./pkg

FROM init AS vet
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN go vet ./[[$app.path]]/... ./pkg/...

# run tests
FROM init AS test
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN go test -coverprofile c.out -v ./[[$app.path]]/... ./pkg/...

# build binary
FROM init AS build
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ARG VERSION=unknown
ARG COMMIT=unknown
ARG BRANCH=unknown
ARG BUILT_AT=unknown
ARG BUILDER=unknown

RUN LDFLAGS="-s -w -X github.com/toozej/monogo/pkg/version.Version=${VERSION} -X github.com/toozej/monogo/pkg/version.Commit=${COMMIT} -X github.com/toozej/monogo/pkg/version.Branch=${BRANCH} -X github.com/toozej/monogo/pkg/version.BuiltAt=${BUILT_AT} -X github.com/toozej/monogo/pkg/version.Builder=${BUILDER}" && \
    CGO_ENABLED=[[$cgo]] go build -o /out/[[$app.binary]] -ldflags="${LDFLAGS}" ./[[$app.mainPath]]
[[- if index $app "writableDirs" ]]
RUN mkdir -p[[ range index $app "writableDirs" ]] /container-root[[.]][[ end ]] && \
    chown -R 65532:65532 /container-root
[[- end ]]

# runtime image including CA certs and tzdata
FROM [[$distroless]]
# Copy our executable.
COPY --from=build /out/[[$app.binary]] /go/bin/[[$app.binary]]
# Include the project license in the runtime image.
COPY LICENSE /usr/share/doc/[[$app.binary]]/copyright
[[- range index $app "writableDirs" ]]
COPY --from=build --chown=65532:65532 /container-root[[.]] [[.]]
[[- end ]]
# Expose port for publishing as web service
[[- if index $app "port" ]]
EXPOSE [[$app.port]]
[[- else ]]
# EXPOSE 8081
[[- end ]]
# Run the binary.
ENTRYPOINT ["/go/bin/[[$app.binary]]"]
