[[- $app := ds "app" -]]
[[- $distroless := $app.distrolessImage -]]
[[- if conv.ToBool (index $app "cgoEnabled") -]][[- $distroless = strings.ReplaceAll "static-" "base-" $distroless -]][[- end -]]
# runtime image including CA certs and tzdata
FROM [[$distroless]]
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/[[$app.binary]] /go/bin/[[$app.binary]]
# Expose port for publishing as web service
[[- if index $app "port" ]]
EXPOSE [[$app.port]]
[[- else ]]
# EXPOSE 8081
[[- end ]]
# Run the binary.
ENTRYPOINT ["/go/bin/[[$app.binary]]"]
