---
services:
  podgrab:
    container_name: podgrab
    image: toozej/podgrab:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      CONFIG: "/config"
      DATA: "/assets"
    ports:
      - "8080:8080"
    volumes:
      - "podgrab-config:/config"
      - "podgrab-assets:/assets"
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.podgrab.rule=Host(`podgrab.test`)"
      # - "traefik.http.routers.podgrab.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.podgrab-secure.entrypoints=https"
      # - "traefik.http.routers.podgrab-secure.rule=Host(`podgrab.test`)"
      # - "traefik.http.routers.podgrab-secure.middlewares=headers@file"
      # - "traefik.http.routers.podgrab-secure.tls=true"
    # networks:
      # - traefik
volumes:
  podgrab-config:
  podgrab-assets:
