# runtime image
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/podgrab /go/bin/podgrab
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/podgrab"]
