# runtime image
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/rss2socials /go/bin/rss2socials
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/rss2socials"]
