# runtime image
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/RSSFFS /go/bin/RSSFFS
# Expose port for publishing as web service
EXPOSE 8080
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/RSSFFS"]
