# runtime image including CA certs and tzdata
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/RSSFFS /go/bin/RSSFFS
# Include the project license in the runtime image.
COPY LICENSE /usr/share/doc/RSSFFS/copyright
# Expose port for publishing as web service
EXPOSE 8080
# Run the binary.
ENTRYPOINT ["/go/bin/RSSFFS"]
