# runtime image including CA certs and tzdata
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/gotts-it /go/bin/gotts-it
# Set working directory for output files
WORKDIR /out
# Run the binary.
ENTRYPOINT ["/go/bin/gotts-it"]
