# runtime image
FROM scratch
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/ghreleases2rss /go/bin/ghreleases2rss
# Run the binary.
USER nonroot
ENTRYPOINT ["/go/bin/ghreleases2rss"]
