# runtime image
FROM scratch
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/golang-starter /go/bin/golang-starter
# Include the project license in the runtime image.
COPY LICENSE /usr/share/doc/golang-starter/copyright
# Expose port for publishing as web service
# EXPOSE 8081
# Verify that the application binary can start without requiring a shell or
# additional utilities in the minimal runtime image.
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 \
    CMD ["/go/bin/golang-starter", "version"]
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/golang-starter"]
