# runtime image including CA certs and tzdata
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/golang-starter /go/bin/golang-starter
# Include the project license in the runtime image.
COPY LICENSE /usr/share/doc/golang-starter/copyright
# Expose port for publishing as web service
# EXPOSE 8081
# Run the binary.
ENTRYPOINT ["/go/bin/golang-starter"]
