# runtime image
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/url2anki /go/bin/url2anki
# Include the project license in the runtime image.
COPY LICENSE /usr/share/doc/url2anki/copyright
# Expose port for publishing as web service
# EXPOSE 8081
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/url2anki"]
