# runtime image
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/url2anki /go/bin/url2anki
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/url2anki"]
