# runtime image
FROM scratch
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/trails-completionist /go/bin/trails-completionist
# Include the project license in the runtime image.
COPY LICENSE /usr/share/doc/trails-completionist/copyright
# Expose port for publishing as web service
# EXPOSE 8081
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/trails-completionist"]
