[build]
cmd = "task local:reload APP=go-sort-out-gh-actions"

include_ext = ["go", "tpl", "tmpl", "html"]

exclude_dir = ["assets", "tmp", "vendor", "testdata", "out", "dist"]

[misc]
clean_on_exit = true
