# runtime image
FROM gcr.io/distroless/static-debian13:latest
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/go-sort-out-gh-actions /go/bin/go-sort-out-gh-actions
# Include the project license in the runtime image.
COPY LICENSE /usr/share/doc/go-sort-out-gh-actions/copyright
# Expose port for publishing as web service
# EXPOSE 8081
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/go-sort-out-gh-actions"]
