---
services:
  monogo:
    container_name: monogo
    image: toozej/monogo:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.monogo.rule=Host(`monogo.test`)"
      # - "traefik.http.routers.monogo.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.monogo-secure.entrypoints=https"
      # - "traefik.http.routers.monogo-secure.rule=Host(`monogo.test`)"
      # - "traefik.http.routers.monogo-secure.middlewares=headers@file"
      # - "traefik.http.routers.monogo-secure.tls=true"
    # networks:
      # - traefik
