# runtime image
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/go-listen /go/bin/go-listen
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/go-listen"]
