---
services:
  go-listen:
    container_name: go-listen
    image: toozej/go-listen:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    environment:
      SECURITY_PASSWORD: "${SECURITY_PASSWORD:?set SECURITY_PASSWORD}"
      SECURITY_USERNAME: "${SECURITY_USERNAME:-go-listen}"
      SERVER_HOST: "0.0.0.0"
      SPOTIFY_CLIENT_ID: "${SPOTIFY_CLIENT_ID:?set SPOTIFY_CLIENT_ID}"
      SPOTIFY_CLIENT_SECRET: "${SPOTIFY_CLIENT_SECRET:?set SPOTIFY_CLIENT_SECRET}"
      SPOTIFY_REDIRECT_URL: "${SPOTIFY_REDIRECT_URL:-http://localhost:8080/callback}"
      SPOTIFY_TOKEN_FILE: "/config/spotify-token.json"
    ports:
      - "8080:8080"
    volumes:
      - "go-listen-config:/config"
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.go-listen.rule=Host(`go-listen.test`)"
      # - "traefik.http.routers.go-listen.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.go-listen-secure.entrypoints=https"
      # - "traefik.http.routers.go-listen-secure.rule=Host(`go-listen.test`)"
      # - "traefik.http.routers.go-listen-secure.middlewares=headers@file"
      # - "traefik.http.routers.go-listen-secure.tls=true"
    # networks:
      # - traefik
volumes:
  go-listen-config:
