# runtime image
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/go-find-liquor /go/bin/go-find-liquor
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/go-find-liquor"]
