---
services:
  gotts-it:
    container_name: gotts-it
    image: toozej/gotts-it:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: true
    depends_on:
      - speaches
    env_file:
      - gotts-it.env
    command: ["server", "--output-dir", "/out"]
    stdin_open: true
    volumes:
      - ./out:/out
    networks:
      - backend
      # - traefik
    labels:
      - "traefik.enable=false"
      # labels below for publishing as web service
      # - "traefik.docker.network=traefik"
      # - "traefik.http.routers.gotts-it.rule=Host(`gotts-it.test`)"
      # - "traefik.http.routers.gotts-it.middlewares=http-redirect-https@file,headers@file"
      # - "traefik.http.routers.gotts-it-secure.entrypoints=https"
      # - "traefik.http.routers.gotts-it-secure.rule=Host(`gotts-it.test`)"
      # - "traefik.http.routers.gotts-it-secure.middlewares=headers@file"
      # - "traefik.http.routers.gotts-it-secure.tls=true"

  speaches:
    container_name: speaches
    image: ghcr.io/speaches-ai/speaches:latest-cpu
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - hf-hub-cache:/home/ubuntu/.cache/huggingface/hub
    networks:
      - backend
    ports:
      - 8000:8000
    labels:
      - "traefik.enable=false"

networks:
  backend:
    driver: bridge


volumes:
  hf-hub-cache:
