# runtime image including CA certs and tzdata
FROM gcr.io/distroless/static-debian13:nonroot
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/photos2map /go/bin/photos2map
# Include the project license in the runtime image.
COPY LICENSE /usr/share/doc/photos2map/copyright
# Expose port for publishing as web service
# EXPOSE 8081
# Run the binary.
ENTRYPOINT ["/go/bin/photos2map"]
