# runtime image
FROM scratch
# Copy our static executable.
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/files2prompt /go/bin/files2prompt
# Include the project license in the runtime image.
COPY LICENSE /usr/share/doc/files2prompt/copyright
# Expose port for publishing as web service
# EXPOSE 8081
# Run the binary.
USER 65532:65532
ENTRYPOINT ["/go/bin/files2prompt"]
